### ISSUE TITLE
ヒットアンドブローの数値回答が常に受け付けられている

### ISSUE THREAD

**Issue by Fukusan64** [kp54/mute-bot#1]
https://github.com/kp54/mute-bot/blob/11e6d41acda05c2e1d8fc8e801f1a460fe7214fd/src/features/hit-and-blow/index.ts#L103
4桁の数値が何でもヒットアンドブローの回答だと思われている

**Comment by kp54** [comment]
`^` / `$`と `|` の優先順位によって `/hb.*` `.*[0-9]{4}` にマッチしている問題はコミット 0dae7e12555aabec72ecee1c6ce62b3bda698351 で修正しました。
N 桁の数字へのマッチは常に行いますが、進行中のゲームがなかった場合無視するよう実装しています。

**Comment by Fukusan64** [comment]
悲しいが
何故か、ゲームのスレッド外でも反応している…

**Comment by kp54** [comment]
修正しました。 50ad3e19b0c4314c8ac32fa273ca3bf98ac1ef6b
ゲーム中か否かのテストの前にスレッドを作成していました。

**Comment by Fukusan64** [comment]
なるほど
対応ありがとうございます
